# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('kcal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('carb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
