# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addNoms', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
