# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addNoms', '0003_user_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(max_length=500)),
                ('kcal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('carb', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
