# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addNoms', '0005_journal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='JournalEntry',
        ),
    ]
